### PR TITLE
fix gnutls cert error

### PR DESCRIPTION
**Pull request by tarkah**
think i figured out how to get the cert to work!

### CODE REVIEW

**Comment by tarkah** [comment]
I added a build script for creating the docker image, which makes sure the hosts are set correctly. This will also need to be ran when running the container as well. Not sure if you're interested in eventually supplying a Docker Compose file?

**Comment by taylor-verys** [comment]
I'm interested in learning what a Compose file does! Haha seriously though whatever helps to make this thing smoother that would be great. I was actually editing the hosts file on my unraid machine – if this works how I think it does then this is 100 times better because it's one less thing we have to document.

**Comment by taylorbourne** [comment]
I'm interested in learning what a Compose file does! Haha seriously though whatever helps to make this thing smoother that would be great. I was actually editing the hosts file on my unraid machine – if this works how I think it does then this is 100 times better because it's one less thing we have to document. Sorry deleted my previous comment as I made it using the wrong account.

**Comment by tarkah** [comment]
So the --add-host in the build script is only good for the build. It'd need to be passed in the `docker run` as well.

Docker compose is basically a layer of `docker run`, it allows you to specify a ton of configuration options. I think it'll be easier to tell people, run `docker-compose up` instead of `docker run` + a shit ton of flags.

**Comment by tarkah** [comment]
I'm not sure we can dynamically get the IP of freegamez.ga for the docker-compose.yml file, but we can at least list it statically and it should be easy to update when changes.  Or maybe the entrypoint.sh can dynamically make sure the hosts file is current

**Comment by tarkah** [comment]
Eh, maybe docker-compose isn't really needed. Seems mostly useful for when you have multiple images you need to run together under one umbrella.

**Comment by tarkah** [comment]
I say you just make a run.sh script for people to use that has all the `docker run` flags set. We can also have it dynamically set the hosts then, like I've done in the build.sh file

**Comment by tarkah** [comment]
So I changed things up. Instead of setting hosts and updating the certs when the container is built, its probably best to do it when its run / at the entrypoint level so it's ALWAYS up to date. I've added run.sh to stand in for `docker run`

**Comment by taylorbourne** [comment]
Nice work man, will get this merged when I get home from dinner. This is actually better for me since I use unraid, ensures everything gets added properly. I might add some changes to the readme since hosts file doesn’t need to be updated. Other than that, 👍🏽

**Pull request merged**
