### PR TITLE
bump lazystream with logos fix

### LINKED ISSUE #27: NHL logo not resolving
I see that the URL http://home.windstream.net/dgrodecki/images/nhl/nhl_logo2.jpg is used as the logo for the channels however it seems to not be loading. Is this expected? Btw thanks for all the work on this!

### PR DESCRIPTION
**Pull request by tarkah**
resolves #27

### CODE REVIEW

**Comment by taylorbourne** [comment]
@tarkah haha you're awesome.. my team (Ducks) has their first game today. When I started my workday I went to look at your repo first to see if things were still running and noticed that you had made some changes and was going to get that in. Thanks again, dude! Going to restart my xTeVe and plex servers to see if games start populating.. can't remember if the guide data should be updated already or if that doesn't happen until right before game time.

**Comment by taylorbourne** [comment]
Ah, I think I'll also have to cut a release – I'll get to that this afternoon.

**Comment by tarkah** [comment]
Haha no problem. Things seem to still work from last season thankfully! And good luck, I'm a VGK fan :)

**Comment by taylorbourne** [comment]
@tarkah since this is kind of a minor fix I'll likely wait until after the games tonight to cut a fix. I'm too scared of breaking things before game time :D 

Haha I don't think I knew you were a VGK fan! Good luck tonight

**Pull request merged**
