### PR TITLE
bump lazystream

### PR DESCRIPTION
**Pull request by tarkah**
has xmltv fixes

- Create records for ALL games scheduled for the day, even
    if the stream doesn't exist yet.
- Update programme start time to be accurate

### CODE REVIEW

**Comment by taylor-verys** [comment]
🎉 bump it up

**Comment by tarkah** [comment]
Sweet!

FYI, I'm facing a bug where Plex isn't getting updated EPG data from xTeVe, as noted here:

https://github.com/xteve-project/xTeVe-Documentation/blob/master/en/troubleshooting.md#plex-dvr-can-not-be-set-up-or-channels-are-missing

My workaround is to bind mount my .xteve/data folder to my Plex docker and specify the `xteve.xml` file directly when setting up the tuner in Plex. You might want to add that to the README

**Comment by taylorbourne** [comment]
I've always done the same to avoid that bug – I'll update the readme. Though I started over from scratch and now my streams wont play?

**Comment by taylorbourne** [comment]
```
[xTeVe] VLC log:               [00005567a6486aa0] gnutls tls client error: Certificate verification failure: The certificate is NOT trusted. The name in the certificate does not match the expected.
2020-03-05 18:55:27 [xTeVe] VLC log:               [00005567a6486aa0] main tls client error: connection error: Permission denied
2020-03-05 18:55:27 [xTeVe] VLC log:               [00005567a6229840] main demux error: no suitable access module for `https://mf.svc.nhl.com:443/ws/media/mf/v2.3/key/silk/mediaid/71471203/kid/70316466'
2020-03-05 18:55:27 [xTeVe] VLC log:               [00005567a67f0760] main tls client error: TLS session handshake error
2020-03-05 18:55:27 [xTeVe] VLC log:               [00005567a675f8e0] access stream error: HTTP connection failure
```
Getting this so seems like my certs aren't set up properly?

**Comment by tarkah** [comment]
Huh, shouldn't be, the certs get updated every time the container is booted up

**Comment by tarkah** [comment]
Have you reset the container in the last day? I think let's encrypt just expired a TON of certs recently

**Comment by tarkah** [comment]
https://www.google.com/url?q=https://community.letsencrypt.org/t/revoking-certain-certificates-on-march-4/114864&sa=U&ved=2ahUKEwiflrTbiYXoAhWEq54KHS8ND7UQFjAAegQICRAB&usg=AOvVaw3pjA_QC9AAQ-xmLsmKEEf1

**Comment by taylorbourne** [comment]
Yeah I had recently fired it all up.. I’ll wait for tonight’s games to get some more testing in.

**Comment by tarkah** [comment]
Sounds good.

The 10:05 Red Sox / Braves game is working for me right now. My guide updated today with all the games, too :)

**Comment by taylorbourne** [comment]
Ah.. something is failing 

```
2020/03/06 17:33:13 [xTeVe] [ERROR] stat playlists/lazystream/lazystream-nhl.xml: no such file or directory () - EC: 0
```

Not sure why this is throwing since that file does exist lol

**Comment by taylorbourne** [comment]
Even with that fixed up.. still getting this over and over again
```
2020/03/06 18:39:12 [xTeVe] VLC log: [000055d5a53d3c00] main tls client error: TLS session handshake error

2020/03/06 18:39:12 [xTeVe] VLC log: [000055d5a53d3c00] main tls client error: connection error: Permission denied

2020/03/06 18:39:12 [xTeVe] VLC log: [000055d5a56be3a0] access stream error: HTTP connection failure

2020/03/06 18:39:12 [xTeVe] VLC log: [000055d5a52008c0] main demux error: no suitable access module for `https://mf.svc.nhl.com:443/ws/media/mf/v2.3/key/silk/mediaid/71302003/kid/70305303'

2020/03/06 18:39:12 [xTeVe] VLC log: [000055d5a53d4420] gnutls tls client error: Certificate verification failure: The certificate is NOT trusted. The name in the certificate does not match the expected.
``` 
Huge bummer, this was working fine the other day

**Comment by taylorbourne** [comment]
```
[cont-init.d] 10-adduser: exited 0.
[cont-init.d] 40-install-defaults: executing...
[cont-init.d] 40-install-defaults: exited 0.
[cont-init.d] 50-update-hosts: executing...
[update-hosts] # Generated
[update-hosts] 127.0.0.1 tayshserve localhost
[update-hosts] 54.149.176.35 keys.lime-technology.com
[update-hosts] 165.22.201.101 playback.svcs.mlb.com
[update-hosts] 165.22.201.101 mf.svc.nhl.com
[update-hosts] 165.22.201.101 mlb-ws-mf.media.mlb.com
[update-hosts] Processed 150 CA certificate(s).
Host playback.svcs.mlb.com (https) has never been contacted before.
Its certificate is valid for playback.svcs.mlb.com.
[update-hosts] Resolving 'playback.svcs.mlb.com:443'...
[update-hosts] Connecting to '165.22.201.101:443'...
[update-hosts] - Certificate type: X.509
[update-hosts] - Got a certificate list of 2 certificates.
[update-hosts] - Certificate[0] info:
[update-hosts] - subject `CN=freegamez.ga', issuer `CN=Let's Encrypt Authority X3,O=Let's Encrypt,C=US', serial 0x0490c48441dce6757147941122d7767e83e5, RSA key 2048 bits, signed using RSA-SHA256, activated `2020-01-13 15:46:46 UTC', expires `2020-04-12 15:46:46 UTC', pin-sha256="F78b6VmOlodrXTaD0ytTh1ApOMOkJkgyYB/4ZTGv1uI="
[update-hosts] Public Key ID:
[update-hosts] sha1:f88fa6fa422e1eaec67aa6db2a8a328817cde1a9
[update-hosts] sha256:17bf1be9598e96876b5d3683d32b5387502938c3a4264832601ff86531afd6e2
[update-hosts] Public Key PIN:
[update-hosts] pin-sha256:F78b6VmOlodrXTaD0ytTh1ApOMOkJkgyYB/4ZTGv1uI=
[update-hosts]
[update-hosts] - Certificate[1] info:
[update-hosts] - subject `CN=Let's Encrypt Authority X3,O=Let's Encrypt,C=US', issuer `CN=DST Root CA X3,O=Digital Signature Trust Co.', serial 0x0a0141420000015385736a0b85eca708, RSA key 2048 bits, signed using RSA-SHA256, activated `2016-03-17 16:40:46 UTC', expires `2021-03-17 16:40:46 UTC', pin-sha256="YLh1dUR9y6Kja30RrAn7JKnbQG/uEtLMkBgFF2Fuihg="
[update-hosts] - Status: The certificate is NOT trusted. The name in the certificate does not match the expected.
[update-hosts] *** PKI verification of server certificate failed...

[update-hosts] - Description: (TLS1.2)-(ECDHE-X25519)-(RSA-PSS-RSAE-SHA256)-(CHACHA20-POLY1305)
[update-hosts] - Session ID: 5B:D1:44:E0:AE:6B:9A:7A:3B:A0:9D:F8:AC:69:7A:96:11:55:07:7B:F7:0F:9C:4D:29:85:CA:0F:55:29:55:06
[update-hosts] - Options: extended master secret, safe renegotiation,
[update-hosts] - Handshake was completed
[update-hosts]
[update-hosts] - Simple Client Mode:
[update-hosts]
[update-hosts] - Peer has closed the GnuTLS connection
[update-hosts] Processed 150 CA certificate(s).
[update-hosts] Resolving 'mf.svc.nhl.com:443'...
[update-hosts] Connecting to '165.22.201.101:443'...
[update-hosts] - Certificate type: X.509
[update-hosts] - Got a certificate list of 2 certificates.
[update-hosts] - Certificate[0] info:
[update-hosts] - subject `CN=freegamez.ga', issuer `CN=Let's Encrypt Authority X3,O=Let's Encrypt,C=US', serial 0x0490c48441dce6757147941122d7767e83e5, RSA key 2048 bits, signed using RSA-SHA256, activated `2020-01-13 15:46:46 UTC', expires `2020-04-12 15:46:46 UTC', pin-sha256="F78b6VmOlodrXTaD0ytTh1ApOMOkJkgyYB/4ZTGv1uI="
[update-hosts] Public Key ID:
[update-hosts] sha1:f88fa6fa422e1eaec67aa6db2a8a328817cde1a9
[update-hosts] sha256:17bf1be9598e96876b5d3683d32b5387502938c3a4264832601ff86531afd6e2
[update-hosts] Public Key PIN:
[update-hosts] pin-sha256:F78b6VmOlodrXTaD0ytTh1ApOMOkJkgyYB/4ZTGv1uI=
[update-hosts]
[update-hosts] - Certificate[1] info:
Are you sure you want to trust it? (y/N): Host mf.svc.nhl.com (https) has never been contacted before.
Its certificate is valid for mf.svc.nhl.com.
[update-hosts] - subject `CN=Let's Encrypt Authority X3,O=Let's Encrypt,C=US', issuer `CN=DST Root CA X3,O=Digital Signature Trust Co.', serial 0x0a0141420000015385736a0b85eca708, RSA key 2048 bits, signed using RSA-SHA256, activated `2016-03-17 16:40:46 UTC', expires `2021-03-17 16:40:46 UTC', pin-sha256="YLh1dUR9y6Kja30RrAn7JKnbQG/uEtLMkBgFF2Fuihg="
[update-hosts] - Status: The certificate is NOT trusted. The name in the certificate does not match the expected.
[update-hosts] *** PKI verification of server certificate failed...

[update-hosts] - Description: (TLS1.2)-(ECDHE-X25519)-(RSA-PSS-RSAE-SHA256)-(CHACHA20-POLY1305)
[update-hosts] - Session ID: 25:0D:C8:F6:8C:01:91:4D:BD:23:BA:0C:6C:40:E2:2A:86:10:AB:79:48:82:39:00:B0:7A:C9:0C:32:E1:AB:A6
[update-hosts] - Options: extended master secret, safe renegotiation,
[update-hosts] - Handshake was completed
[update-hosts]
[update-hosts] - Simple Client Mode:
[update-hosts]
[update-hosts] - Peer has closed the GnuTLS connection
[update-hosts] Processed 150 CA certificate(s).
[update-hosts] Resolving 'mlb-ws-mf.media.mlb.com:443'...
[update-hosts] Connecting to '165.22.201.101:443'...
[update-hosts] - Certificate type: X.509
[update-hosts] - Got a certificate list of 2 certificates.
[update-hosts] - Certificate[0] info:
[update-hosts] - subject `CN=freegamez.ga', issuer `CN=Let's Encrypt Authority X3,O=Let's Encrypt,C=US', serial 0x0490c48441dce6757147941122d7767e83e5, RSA key 2048 bits, signed using RSA-SHA256, activated `2020-01-13 15:46:46 UTC', expires `2020-04-12 15:46:46 UTC', pin-sha256="F78b6VmOlodrXTaD0ytTh1ApOMOkJkgyYB/4ZTGv1uI="
[update-hosts] Public Key ID:
Are you sure you want to trust it? (y/N): Host mlb-ws-mf.media.mlb.com (https) has never been contacted before.
Its certificate is valid for mlb-ws-mf.media.mlb.com.
[update-hosts] sha1:f88fa6fa422e1eaec67aa6db2a8a328817cde1a9
[update-hosts] sha256:17bf1be9598e96876b5d3683d32b5387502938c3a4264832601ff86531afd6e2
[update-hosts] Public Key PIN:
[update-hosts] pin-sha256:F78b6VmOlodrXTaD0ytTh1ApOMOkJkgyYB/4ZTGv1uI=
[update-hosts]
[update-hosts] - Certificate[1] info:
[update-hosts] - subject `CN=Let's Encrypt Authority X3,O=Let's Encrypt,C=US', issuer `CN=DST Root CA X3,O=Digital Signature Trust Co.', serial 0x0a0141420000015385736a0b85eca708, RSA key 2048 bits, signed using RSA-SHA256, activated `2016-03-17 16:40:46 UTC', expires `2021-03-17 16:40:46 UTC', pin-sha256="YLh1dUR9y6Kja30RrAn7JKnbQG/uEtLMkBgFF2Fuihg="
[update-hosts] - Status: The certificate is NOT trusted. The name in the certificate does not match the expected.
[update-hosts] *** PKI verification of server certificate failed...

[update-hosts] - Description: (TLS1.2)-(ECDHE-X25519)-(RSA-PSS-RSAE-SHA256)-(CHACHA20-POLY1305)
[update-hosts] - Session ID: E3:91:F0:DA:6F:4B:0B:53:D9:F5:FD:40:37:EC:1B:2B:58:5B:A5:13:13:E3:98:C0:D1:7D:FC:DA:13:3F:A7:6E
[update-hosts] - Options: extended master secret, safe renegotiation,
[update-hosts] - Handshake was completed
[update-hosts]
[update-hosts] - Simple Client Mode:
[update-hosts]
[update-hosts] - Peer has closed the GnuTLS connection
[update-hosts] |g0|playback.svcs.mlb.com|https|0|MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAvXwbDLbBZGAkb+Byw6TtwkkMs2HuKKnItAkgI3mI5DHtGIIcA3vfNvEs5KDK1LylXEZecD5I/pQUwDa0ftxp/+gc6xcLhk76/DgHgIlkC8A2jrCPxPdQupZGVWiJb4vJQHOfoEADZ+rny6jvzO9ZLUuC9Ztp6MzHp57w3czEMpwE2hdg+thAt3G76+WZ8lOP1Q6ZNVWUmoAiAwxepiB0jRwiUliED3seglKGWOjKAYw0X2NAMdTRj1yl0RD5I0fsiz0ZT6+OKa7KmcFfAxKQYFtfCfGD5coEP/nbVeO2v6tHO78H62W0bsvmjwSCEtgT108kzuGHQCuhB2DJu+Xt3QIDAQAB
[update-hosts] |g0|mf.svc.nhl.com|https|0|MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAvXwbDLbBZGAkb+Byw6TtwkkMs2HuKKnItAkgI3mI5DHtGIIcA3vfNvEs5KDK1LylXEZecD5I/pQUwDa0ftxp/+gc6xcLhk76/DgHgIlkC8A2jrCPxPdQupZGVWiJb4vJQHOfoEADZ+rny6jvzO9ZLUuC9Ztp6MzHp57w3czEMpwE2hdg+thAt3G76+WZ8lOP1Q6ZNVWUmoAiAwxepiB0jRwiUliED3seglKGWOjKAYw0X2NAMdTRj1yl0RD5I0fsiz0ZT6+OKa7KmcFfAxKQYFtfCfGD5coEP/nbVeO2v6tHO78H62W0bsvmjwSCEtgT108kzuGHQCuhB2DJu+Xt3QIDAQAB
[update-hosts] |g0|mlb-ws-mf.media.mlb.com|https|0|MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAvXwbDLbBZGAkb+Byw6TtwkkMs2HuKKnItAkgI3mI5DHtGIIcA3vfNvEs5KDK1LylXEZecD5I/pQUwDa0ftxp/+gc6xcLhk76/DgHgIlkC8A2jrCPxPdQupZGVWiJb4vJQHOfoEADZ+rny6jvzO9ZLUuC9Ztp6MzHp57w3czEMpwE2hdg+thAt3G76+WZ8lOP1Q6ZNVWUmoAiAwxepiB0jRwiUliED3seglKGWOjKAYw0X2NAMdTRj1yl0RD5I0fsiz0ZT6+OKa7KmcFfAxKQYFtfCfGD5coEP/nbVeO2v6tHO78H62W0bsvmjwSCEtgT108kzuGHQCuhB2DJu+Xt3QIDAQAB
[cont-init.d] 50-update-hosts: exited 0.
[cont-init.d] 60-chown-files: executing...
[cont-init.d] 60-chown-files: exited 0.
[cont-init.d] done.
[services.d] starting services
[crond-setup] No cron definition found...
[crond-setup] By default, cronjob will run every night at midnight unless cron file is configured.
For help run: ./xteve -h```
Yep, certs are failing

**Comment by taylorbourne** [comment]
Also getting permissions errors..
```
2020-03-06 18:40:55 [xTeVe] Backup Path:           /root/.xteve/backup/
2020-03-06 18:40:55 [xTeVe] [ERROR] open /root/.xteve/backup/: permission denied (Automatic backup failed) - EC: 1090
```
 lol I can't win

**Comment by tarkah** [comment]
Why is xTeVe trying to access /root/.xteve?? I changed it to set config home to /xteve volume

**Comment by tarkah** [comment]
Something doesn't seem right on your end at all....

**Comment by taylorbourne** [comment]
Ah.. I bet it's because I restored my backup – still, certs should be going through right?

**Comment by tarkah** [comment]
I'm using ffmpeg, not VLC. The default config that's shipped has ffmpeg working.

**Comment by tarkah** [comment]
Maybe just copy your device UUID, delete your config folder, and have it generate the default and fill your UUID back in?

**Comment by taylorbourne** [comment]
Ah yep, fresh install using FFMPEG works like a charm. Something must be up with VLC. 🤷‍♂

**Comment by tarkah** [comment]
Sweet! We could always remove the VLC binary since it's clearly not recommended to use it in this setup

**Comment by taylorbourne** [comment]
Lol yeah I just decided to start over from scratch.. all of my xteve filters were kinda trash anyway, going to redo everything nice and clean. Currently watching my Ducks successfully 👍

**Comment by tarkah** [comment]
@taylorbourne  how has it been running for you the past few days? It's been rock solid for me! You should post this to the subreddit soon :)

**Comment by taylorbourne** [comment]
Things are pretty good! I had some weird things happen the last time I tried to watch a game (Tuesday night). All of the channels were there, but somehow on the live tv settings page Plex had 184 channels mapped with 180 available lol.. so the lazystream channels were “off” – I would select what said the Ducks game and it was something else. I ended up having to do a channel scan in plex followed by a guide refresh.

**Comment by tarkah** [comment]
Hmm, that is weird. Why do you only have 180 available instead of the full 200?

**Pull request merged**
