### PR TITLE
move to s6 overlay structure

### PR DESCRIPTION
**Pull request by tarkah**
So this is a pretty comprehensive cleanup of how everything is initialized and ran.

I am using https://github.com/just-containers/s6-overlay as a template to run / supervise everything, I highly recommend reading through the README. I think the structure makes this entire thing much easier to maintain.

Basically, everything now works as follows:

- The new `root` folder is coped to the container on build
- We no longer need an entrypoint, the project runs through the scripts specified in `cont-init.d` on startup, and supervises the services listed in `services.d`
- `crond` is now run in the foreground and supervised by s6, and output from that job is pushed to stdout, which satisfies #12 
- I've removed the ability for users to edit the `cronjob.sh`, they should now reference the `sample.env` file and rename to `.env` in the `/config` volume, which get sourced and picked up in the cronjob. Satisfies #11 
- With this s6 workflow, we now have a user created called `abc`. This user will run the `xteve` service and own permissions to all volumes. We can set the UID and GID of this user to whatever we want with the PUID / PGID variables, which I've set in `run.sh`. Now, all mounted volumes have proper permissions set to the user running the docker.
- The `root/defaults` folder contains file defaults that we can copy to various place (handled by the `40-install-defaults` init script, for example copying `sample*` files to `/config`. I've also included a sane default of xteve's config and blank playlists that get installed properly, so xteve is already all mapped to all 200 channels and setup to use ffmpeg out the gates.
- I've changed the volume mappings in `run.sh` since it was confusing to have things mounted under the `xteve` volume, and I've also moved the `xteve` volume to `/xteve` in the root instead of under the root home, since now it's run by user `abc`.

That mostly covers it, there were things no longer needed in the Dockerfile that got cleaned up. Let me know if you have any questions, but hopefully this makes things much easier to manage.

I've tested this from scratch, removing 100% of my `appdata` files, and after first run, only modifying `cron.txt` and `.env`, then rerunning and it works perfect!

### CODE REVIEW

**Comment by tarkah** [comment]
As some background, the reason I went this route is because I am in love with the various [linuxserver](https://hub.docker.com/u/linuxserver) images, such as their [plex](https://hub.docker.com/r/linuxserver/plex) image. I'm basically copying what they use / using their base alpine image.

It'd be really easy to add this image along with their plex in a `docker compose` setup and have some great automation. Kind of like what was done here [docker-compose-usenet](https://github.com/duhio/docker-compose-usenet)

**Comment by tarkah** [comment]
Hmmm, ffmpeg is failing... looking into this now

**Comment by taylorbourne** [comment]
This is pretty awesome – makes things so much easier to update and maintain. So is the `.env` file able to pull variables from the container? Or does the user have to edit this file to make something happen?

Merge conflict popped up after I merged #10 – should be straight forward.

**Comment by tarkah** [comment]
Thanks! It's broken until I can figure out why ffmpeg isn't working... 

Not sure what you mean by 

> So is the `.env` file able to pull variables from the container? Or does the user have to edit this file to make something happen?

**Comment by taylorbourne** [comment]
I guess a better question would be can I set the variables in the run command with `-e`?

**Comment by tarkah** [comment]
Hmmm, there's probably a way to pickup those variables. And then use those over anything provided in the .env file. Not exactly sure how this would work, but I can play around with it.

**Comment by tarkah** [comment]
Got it working with ffmpeg!! Not sure what was wrong with the other image, but I'm back to using alpine:latest, then just installing the s6 stuff manually vs using that linuxserver base image. I've cleaned up the dockerfile too

**Comment by tarkah** [comment]
rebased onto master

**Comment by tarkah** [comment]
Ok, I have it working with supplying a `.env` file through `docker run --env-file=.env`, or manually supplying `-e VAR=VALUE`. I've added the sample.env to the root of the project. So these can just be documented in the README, and users can either supply them manually or via .env file, but they no longer need to put these in the `/config` volume.

**Comment by tarkah** [comment]
This is better too, because if someone uses this container in `docker compose`, it supports `.env` file inherently and supplying env values in the docker-compose.yml file

**Comment by tarkah** [comment]
Also, weird bug with using `-e` or `--env-file` and this s6 overlay.. the variables didn't work when they were quote wrapped, use_lazystream="yes" vs use_lazystream=yes. I had to remove quotes to get the variables to work in the cronjob.sh with this s6 overlay setup.

**Comment by taylorbourne** [comment]
Amazing.. any other callouts before we go ahead and merge this? I was able to test this out last night and everything seems pretty damn awesome. Now that we can pull variables from `-e` we'll also be able to get a template setup with community applications for Unraid – will make installing this much easier.

**Comment by tarkah** [comment]
I think we are good to go! I finally have this running as a long lived container and it's working great!

**Comment by tarkah** [comment]
Check out latest commit, adds some nice "logging" to std-out, so cron output is in same format as how xteve logs, and the cont-init.d stuff prepends as well, so output all looks nice :)

**Comment by taylorbourne** [comment]
🎉 woo! Going to merge this up right now.. hoping that I can just create a backup of my current xteve setup and restore it to this new container. I have 90+ channels mapped from my IPTV provider as well as the 200 channels from LS – so don't want to lose all of that work.

**Comment by tarkah** [comment]
Also, I'm going to work on this https://github.com/tarkah/lazystream/issues/36 so that you can see / schedule to record upcoming games w/ actual start time for the day, even if stream isn't available yet

**Comment by tarkah** [comment]
Wooo!

**Comment by taylorbourne** [comment]
Nice that will basically bring us up to speed with what you'd get from a real TV provider with an NHL or MLB package 👍

**Pull request merged**
